apiVersion: v1
kind: Secret
metadata:
  name: <k8_db_backup_secret_name>
type: Opaque
data:
  rclone_access_token: <RCLONE_ACCESS_TOKEN | base 64>
  rclone_refresh_token: <RCLONE_REFRESH_TOKEN | base 64>
  rclone_expiry: <RCLONE_EXPIRY | base 64>
  rclone_team_drive: <RCLONE_ACCESS_TOKEN | base 64>
  replicaset: <The name of the replicaset. For standalone server use the name of the database | base 64>
  database: <The name of the database | base 64>
  host: <the host(s) for each member of the replicaset | base 64>
  username: <the user with backup role | base 64>
  password: <the password or the backup user | base 64>
  authdb: <the authentication database | base 64>
